language: go
sudo: required

env:
  global:
    - ORACLE_FILE=instantclient-basic-windows.x64-12.1.0.2.0.zip
    - ORACLE_FILE_2=instantclient-sdk-windows.x64-12.1.0.2.0.zip
    - ORACLE_HOME=/opt/oracle/instantclient_12_1
    - PKG_CONFIG_PATH="."
    - ORACLE_DOWNLOAD_DIR=.cache/oracle
    
cache:
  - directories:
    - .cache/oracle
    
before_install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - >
    { echo "Name: oci8"; echo "Description: Oracle Call Interface"; echo "Version: 12.1";
      echo "Cflags: -I$ORACLE_HOME/sdk/include";
      echo "Libs: -L$ORACLE_HOME/oci.dll";
    } | tee oci8.pc
